package delta.database;

/**
 * Created by lenovo on 16.02.2017.
 */
public interface Queries {
    // Users
    String CREATE_USER = "INSERT INTO USERS (username, passwordhash, description) VALUE (?, ?, ?)";
    String GET_USER_BY_NAME = "SELECT * FROM USERS WHERE USERNAME=?";
    String DELETE_USER = "DELETE FROM USERS WHERE USERNAME=?";
    String UPDATE_USER_PASS = "UPDATE USERS SET PASSWORDHASH=? WHERE USERNAME=?";
    String UPDATE_USER_DESC = "UPDATE USERS SET DESCRIPTION=? WHERE USERNAME=?";
    // Session
    String CREATE_SESSION = "INSERT INTO SESSIONS (id, token, expiration_date) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE " +
                            "token=VALUES(token), expiration_date=VALUES(expiration_date)";
    String GET_SESSION = "SELECT * FROM SESSIONS WHERE token=?";
    String DELETE_SESSION = "DELETE FROM SESSIONS WHERE TOKEN=?";
    // Goods
    String CREATE_GOODS = "INSERT INTO GOODS (name, description, cost) VALUE (?, ?, ?)";
    String GET_GOODS_BY_ID="SELECT * FROM GOODS WHERE ID=?";
    String GET_GOODS_COST="SELECT COST FROM GOODS WHERE ID=?";
    String GET_GOODS="SELECT * FROM GOODS";
    String DELETE_GOODS="DELETE FROM GOODS WHERE ID=?";
    String UPDATE_GOODS="UPDATE GOODS SET COST=? WHERE NAME=?";
    // Orders
    String CREATE_ORDER = "INSERT INTO ORDERS (userid) values (?)";
    String GET_ORDERS = "SELECT * FROM ORDERS WHERE USERID=?";
    String GET_ORDERS_BY_ID = "SELECT USERID FROM ORDERS WHERE ID=?";
    String DELETE_ORDER = "DELETE FROM ORDERS WHERE ID=?";
    // Goods2Orders
    String ADD_GOODS_TO_ORDER = "INSERT INTO GOODS2ORDERS (orderid, goodid) VALUES (?, ?)";
    String DELETE_GOODS_FROM_ORDER = "DELETE FROM GOODS2ORDERS WHERE ORDERID=? AND GOODID=? LIMIT 1";
    String DELETE_ALL_GOODS_FROM_ORDER = "DELETE FROM GOODS2ORDERS WHERE ORDERID=?";
    String DELETE_ALL_ORDERS_OF_GOODS = "DELETE FROM GOODS2ORDERS WHERE GOODID=?";
    String GET_GOODS_IN_ORDER = "SELECT GOODID FROM GOODS2ORDERS WHERE ORDERID=?";
    // Billings
    String CREATE_BILLING = "INSERT INTO BILLINGS (id, cost) VALUES (?, ?) ON DUPLICATE KEY UPDATE cost=VALUES(cost)";
    String GET_BILLINGS = "SELECT A.USERID, A.ID, B.COST FROM ORDERS A, BILLINGS B WHERE A.ID=B.ID AND A.USERID=?";
    String DELETE_BILLING = "DELETE FROM BILLINGS WHERE ID=?";
}
